/**
 * Downloads the webfonts this site uses and writes them into public/fonts/,
 * plus a src/fonts.css with matching @font-face rules.
 *
 * Loading these from fonts.googleapis.com cost ~968ms of render-blocking time and
 * sent every visitor's IP to Google (a GDPR problem the privacy policy calls out).
 * Self-hosting removes both.
 *
 * Only the weights actually used in styles.css are fetched:
 *   Manrope  400/500/600/700 (variable)  — body, headings
 *   DM Mono  400/500                     — kickers, small caps labels
 *   Poppins  600                         — wordmark only
 *
 * Run with `npm run fonts` when a weight or family changes.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

const OUT_DIR = 'public/fonts';
const CSS_OUT = 'src/fonts.css';

// A modern UA is required or Google serves legacy ttf instead of woff2.
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36';

// Keep the subsets that cover European names; drop cyrillic/vietnamese.
const KEEP_SUBSETS = ['latin', 'latin-ext'];

const FAMILIES = [
  { name: 'Manrope', query: 'Manrope:wght@400..700' },
  { name: 'DM Mono', query: 'DM+Mono:wght@400;500' },
  { name: 'Poppins', query: 'Poppins:wght@600' },
];

async function fetchCss(query) {
  const url = `https://fonts.googleapis.com/css2?family=${query}&display=swap`;
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`Google Fonts returned ${res.status} for ${query}`);
  return res.text();
}

/** Splits the returned stylesheet into individual @font-face blocks with their subset comment. */
function parseFaces(css) {
  const faces = [];
  const re = /\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g;
  let match;
  while ((match = re.exec(css)) !== null) {
    faces.push({ subset: match[1], block: match[2] });
  }
  return faces;
}

const pick = (block, prop) => block.match(new RegExp(`${prop}:\\s*([^;]+);`))?.[1]?.trim();

async function run() {
  await mkdir(OUT_DIR, { recursive: true });

  const rules = [];
  let downloaded = 0;
  let totalBytes = 0;

  for (const family of FAMILIES) {
    const css = await fetchCss(family.query);

    for (const face of parseFaces(css)) {
      if (!KEEP_SUBSETS.includes(face.subset)) continue;

      const src = pick(face.block, 'src');
      const remote = src?.match(/url\((https:[^)]+\.woff2)\)/)?.[1];
      if (!remote) continue;

      const weight = pick(face.block, 'font-weight') || '400';
      const style = pick(face.block, 'font-style') || 'normal';
      const unicodeRange = pick(face.block, 'unicode-range');

      const slug = family.name.toLowerCase().replace(/\s+/g, '-');
      const fileName = `${slug}-${weight.replace(/\s+/g, '-')}-${face.subset}.woff2`;

      const bin = await fetch(remote, { headers: { 'User-Agent': UA } });
      if (!bin.ok) throw new Error(`failed to download ${remote}`);
      const buffer = Buffer.from(await bin.arrayBuffer());
      await writeFile(path.join(OUT_DIR, fileName), buffer);

      downloaded += 1;
      totalBytes += buffer.length;
      console.log(`  ${fileName} ${(buffer.length / 1024).toFixed(1)} kB`);

      rules.push(
        [
          '@font-face {',
          `  font-family: '${family.name}';`,
          `  font-style: ${style};`,
          `  font-weight: ${weight};`,
          '  font-display: swap;',
          `  src: url('/fonts/${fileName}') format('woff2');`,
          unicodeRange ? `  unicode-range: ${unicodeRange};` : null,
          '}',
        ]
          .filter(Boolean)
          .join('\n'),
      );
    }
  }

  const header = [
    '/* Generated by scripts/fetch-fonts.mjs — do not edit by hand.',
    ' * Run `npm run fonts` to regenerate after changing weights in that script. */',
    '',
  ].join('\n');

  await writeFile(CSS_OUT, `${header}${rules.join('\n\n')}\n`);
  console.log(
    `\n${downloaded} files, ${(totalBytes / 1024).toFixed(1)} kB total -> ${CSS_OUT}`,
  );
}

run().catch((error) => {
  console.error(error);
  process.exit(1);
});
